In [2]:
import numpy as np

In [1]:
# 1단계 문제
# 크기가 10인 null 벡터를 만드세요. (힌트: np.zeros())
# numpy 버전과 설정을 출력하세요. (힌트: np.__version__, np.show_config())
# 값이 10에서 49까지인 벡터를 만드세요. (힌트: np.arange(10, 50))
# 벡터를 역순으로 만드세요 (첫 번째 요소가 마지막이 됩니다). (힌트: 배열을 뒤집기 위해 [::-1])
# 크기가 3x3이고 0에서 8까지의 값을 갖는 행렬을 만드세요. (힌트: np.arange()와 reshape())

In [7]:
na = np.zeros(10)
na

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.__version__, np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: C:/a/numpy/numpy/.openblas
    version: 0.3.29
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  US

('2.3.0', None)

In [8]:
na1 = np.arange(10,50)
na1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
na1 = na1[::-1]
na1

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
na2 = np.arange(9).reshape(3,3)
na2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 2단계 문제
# 1D 배열을 3x3 행렬로 변환하세요. (힌트: reshape())
# 0에서 1 사이의 랜덤한 값으로 채워진 3x3 배열을 만드세요. (힌트: np.random.random())
# 5x5 단위 행렬을 만드세요. (힌트: np.eye(5))
# 임의의 1D 배열에서 가장 큰 값의 인덱스를 찾으세요. (힌트: np.argmax())
# 크기가 10인 배열을 생성하고, 3에서 8까지의 값을 0으로 바꾸세요. (힌트: 슬라이싱과 배열 인덱싱)

In [12]:
na = np.arange(9)
na = na.reshape(3,3)
na

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
na1 = np.random.random(9).reshape(3,3)
na1

array([[0.17484675, 0.47351091, 0.46182468],
       [0.15618681, 0.96514791, 0.66467146],
       [0.84018929, 0.58366005, 0.39453181]])

In [15]:
na2 = np.eye(5)
na2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
na3 = np.random.random(10)
na3.argmax()

np.int64(9)

In [17]:
na4 = np.arange(10)
na4[3:9] = 0
na4

array([0, 1, 2, 0, 0, 0, 0, 0, 0, 9])

In [ ]:
# 3단계 문제
# 임의의 배열에서 가장 작은 값과 가장 큰 값을 교환하세요. (힌트: np.min(), np.max()와 인덱싱)
# 3차원 배열의 각 슬라이스마다 평균값을 계산하세요. (힌트: np.mean()과 축 설정)
# 크기가 100인 배열을 생성하고 평균, 표준편차를 계산하세요. (힌트: np.mean(), np.std())
# 주어진 2D 배열에서 고유한 행을 찾으세요. (힌트: np.unique()와 axis 설정)
# 임의의 10x10 배열에서 가장 큰 값 5개를 찾으세요. (힌트: np.argsort()와 슬라이싱)

In [20]:
na = np.random.random(10)
print(na)
max_i, min_i = na.argmax(), na.argmin()
na[max_i], na[min_i] = na.min(), na.max()
print(na)

[0.90990651 0.94972986 0.82709807 0.25708301 0.66360964 0.99726529
 0.63620442 0.04055788 0.69939431 0.78992245]
[0.90990651 0.94972986 0.82709807 0.25708301 0.66360964 0.04055788
 0.63620442 0.99726529 0.69939431 0.78992245]


In [39]:
na1 = np.arange(30).reshape(3,2,5)
print(na1)
np.mean(na1, axis=2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


array([[ 2.,  7.],
       [12., 17.],
       [22., 27.]])

In [41]:
na2 = np.arange(100)
print(na2.mean(), na2.std())

49.5 28.86607004772212


In [50]:
na3 = np.arange(100).reshape(10,10)
flat_na3 = na3.flatten()
sorted_na3 = np.argsort(flat_na3)[::-1]
sorted_na3[:5]

array([99, 98, 97, 96, 95])

In [266]:
na4 = np.random.randint(1,21, (4,5))
np.unique(na4,axis=0)

array([[ 8,  8,  8,  6,  6],
       [14, 19, 12, 14, 13],
       [15,  7,  7,  4, 10],
       [18, 17, 18, 13, 18]], dtype=int32)